name: Build and Deploy Blog

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup Node.js for the build script
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Build the blog index
      - name: Build blog index
        run: |
          npm run build

      # Upload the build artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages  # This is the required environment for GitHub Pages
    permissions:
      pages: write        # Required for deploying to GitHub Pages
      id-token: write     # Required for GitHub OIDC authentication
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
